### ISSUE TITLE
[BUG] Women's faces are considerably more blurred than men's faces

### ISSUE THREAD

**Issue by veryprogram** [gianni-rosato/svt-av1-psy#102]
**Overview**
Despite disabling denoising and using a low CRF, women's faces are usually unnaturally blurred while men's faces usually retain more detail. 

**Branch**
In which branch does the issue appear to be occurring?
SVT-AV1-PSY v2.3.0

**Reproduction**
1. Encode a live-action video that depicts both men and women.
2. Zoom in on their faces; notice where the encoder added too much smoothing and therefore created an unrealistic, blurred look.

**Expected behavior**
Fine details on women’s faces — such as pores, vellus hairs, minor flaws in makeup, and small fine lines — should remain visible. 

**Additional context / Relevant Files**
I presume that this is because women are more likely to be wearing full-coverage foundation and concealer, which confuses the encoder by making it perceive those parts of a frame as monolithic; on the other hand, it seems that men’s facial hair, lighter/absent makeup, and generally more pronounced pores/lines/wrinkles make it easier for the encoder to detect that it is not safe to smooth away details in those parts of a frame.

I think the only way to solve this would be implementing facial recognition which instructs the encoder to retain more details wherever faces are detected. It seems unlikely that this could be solved with another heuristic. 

Here are two examples:
<img width="1224" alt="Screenshot 2024-11-22 at 4 56 16 PM" src="https://github.com/user-attachments/assets/de551f6e-d6de-4c1f-9a50-cc18599a298f">
<img width="610" alt="Barbie vs  Ken" src="https://github.com/user-attachments/assets/7da7d640-18fa-4f94-a4c1-746ed62513c0">
(I’ve seen it frequently, but I only have these two on hand at the moment.)

**Comment by BlueSwordM** [comment]
What settings are you using?

**Comment by gianni-rosato** [comment]
Eliminating discrepancies involving skin tones, skin texture, and other human features is important to us and remains on our radar. However, this issue in the way you've presented it would be rather difficult to address and is likely out of scope. Your results could depend on a multitude of different settings that may be responsible for the results you see here. We'll look into addressing this as best we can and re-open this issue accordingly, but in the meantime, our focus will remain on improving perceptual fidelity across a broad set of scenarios. Feel free to take a look at our feature enumeration in the README, our release changelogs, and community updates about SVT-AV1-PSY to see if any of the settings we have introduced may help remedy your situation. We appreciate your patience, and we hope your issue is resolvable through something we've already implemented.
