### ISSUE TITLE
[ENHANCEMENT] Add eta and est. size in encoding progress status

### ISSUE THREAD

**Issue by bex39** [gianni-rosato/svt-av1-psy#17]
**Is your feature request related to a problem? Please describe.**
--progress 2 (aom style) is only show frames, bitrate, and fps

**Describe the solution you'd like**
It would be nice if add info such as time elapsed/eta and est. size

**Describe alternatives you've considered**
SvtAv1EncApp (Patman's build) that included in staxrip has mentioned feature, https://github.com/Patman86/SVT-AV1-Mod-by-Patman/commit/670343f257a1c79bfcdb876ca23021886cd85de0
hope it can be adopted to SVT-AV1-Psy

**Additional context**
![Screenshot 2024-02-11 113539](https://github.com/gianni-rosato/svt-av1-psy/assets/9485189/b5fe8c35-dbba-481e-be30-2b3ef40098b7)

![Screenshot 2024-02-14 211841](https://github.com/gianni-rosato/svt-av1-psy/assets/9485189/4d798ee2-39c4-4842-8d74-fdff1ca4dc53)
 
Thanks.

**Comment by shssoichiro** [comment]
If this is implemented, please be careful that it doesn't break av1an's parsing of the svt command line. We should try to keep this backwards compatible with mainline svt.

**Comment by gianni-rosato** [comment]
I'm in favor of implementing this as a separate `--progress 3` option instead of overriding progress 2. I am a fan of SVT-AV1-PSY attempting to preserve compatibility with mainline to a certain extent, because there could be people using the output of vanilla progress 2 in a specific way where changing it would cause issues for their workflows.

I'll look into merging this to testing & implementing a progress 3 when I have more time

**Comment by gianni-rosato** [comment]
e192425d49e4da053b8c8c605cfd8ba377b50f85

Enjoy! This will be merged to the `master` branch with our first release!

**Comment by bex39** [comment]
> [e192425](https://github.com/gianni-rosato/svt-av1-psy/commit/e192425d49e4da053b8c8c605cfd8ba377b50f85)
> 
> Enjoy! This will be merged to the `master` branch with our first release!

Nice, thank you 👍
