### ISSUE TITLE
[BUG] Sigmoidal QM curve for tune 3 seems to be missing parantheses

### ISSUE THREAD

**Issue by WhitePeter** [gianni-rosato/svt-av1-psy#95]
> Just a passerby here. I cannot help but wonder if there are some parentheses missing?
> 
> Taking into account operator precedence the formula as it stands now is equivalent to `2 + exp(0.01 * qindex)`, so the `/ 1` part is redundant. Having only a passing knowledge about sigmoidal curves I am not sure if it should be `2 / (1 + exp(0.01 * qindex))` but it looks like it. 

 _Originally posted by @WhitePeter in [119dab2](https://github.com/gianni-rosato/svt-av1-psy/commit/119dab2d5f454473d86443a783d8c7c0f19aea00#r148913597)_

---

Please see above code comment. If I am mistaken just disregard my post.

**Comment by gianni-rosato** [comment]
Hi there,

Thanks for the issue report. We will look into this as soon as possible.

**Comment by Clybius** [comment]
Hello! Thanks for writing in the bug report, you've got a great eye for spotting this! Will push the fix ASAP into the testing branch.

The following graphs are representations of the functions before/after. The y-axis represents the resulting QM value, and the x-axis represents the given base_qindex.

Previous, incorrect curve. The red line indicates the luma formula, and the orange line indicates the chroma formula. The chroma formula has since been removed due to the introduction of a separate qm param, chroma-qm-min, and its default of `8`.
![Screenshot_20241109_103006](https://github.com/user-attachments/assets/28b50e0f-a1a0-4ed1-aad0-39cd2fbe1f6d)

New, updated and correct curve.
![Screenshot_20241109_103910](https://github.com/user-attachments/assets/dc465654-2934-46e6-bdde-1dde7ef9e849)

[Interactive Desmos](https://www.desmos.com/calculator/xtpldlnee6) for learning how qm-min/max interact across qindexes.

For a given CRF before/after this patch, the bitrate may slightly rise (about a 6% increase, will likely vary depending on your source and CRF), though it does seem to improve detail as a result of both the formula change and the slightly increased allocation of bitrate.

If there are any unexpected results, feel free to let us know!

**Comment by WhitePeter** [comment]
Ahh, gotta love open source. Went out for a walk and came back to find this addressed already, on a weekend no less. Great!

**Comment by gianni-rosato** [comment]
Your attention to detail is impressive, I'm surprised this was discovered in the first place! Thank you!

**Comment by WhitePeter** [comment]
Right back at you. If it weren't for the detailed changelog I wouldn't have looked.

**Comment by BlueSwordM** [comment]
@WhitePeter Thanks a lot for the help :)
